### ISSUE TITLE
Not a way to install the extension 

### ISSUE THREAD

**Issue by Solusan** [Zer0CoolX/guacamole-customize-loginscreen-extension#8]
Hello,

I tried to install this extension in ubuntu 18.04 and after execute this command:

$ semanage fcontext -a -t tomcat_exec_t "/etc/guacamole/extensions/branding.jar"
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 28, in <module>
    import seobject
  File "/usr/lib/python3/dist-packages/seobject.py", line 1039, in <module>
    class portRecords(semanageRecords):
  File "/usr/lib/python3/dist-packages/seobject.py", line 1041, in portRecords
    valid_types = list(list(sepolicy.info(sepolicy.ATTRIBUTE, "port_type"))[0]["types"])
  File "/usr/lib/python3/dist-packages/sepolicy/__init__.py", line 196, in <genexpr>
    return ({
  File "/usr/lib/python3/dist-packages/setools/typeattrquery.py", line 65, in results
    for attr in self.policy.typeattributes():
AttributeError: 'NoneType' object has no attribute 'typeattributes'

_____

Even restarted guacad and tomcat9, I cannot get the jar I edited.

I tried to coping it to /etc/guacamole/extensions/branding.jar end disable SElinux with no success.

Any idea?

Thanks a lot.

**Comment by Zer0CoolX** [comment]
1. Unless it has recently changed, Ubuntu does not use SEL, so the `semanage` commands do not apply to your use. Ubuntu might use App Armour which is similar but...A, uses different commands to work with and B, I know nothing about setting it properly.
2. Verify what your GUACAMOLE_HOME location is (https://guacamole.apache.org/doc/gug/configuring-guacamole.html). Typically its `/etc/guacamole` but not always. Within GUACAMOLE_HOME should be an `/extensions` folder (IE: `/etc/guacamole/extensions`). All of your guacamole extensions should be placed here and they are loaded in alphabetical order. Make sure branding.jar is alphabetically before all others in this folder.

> I cannot get the jar I edited.

This does not make sense, you would edit the jar (modify the extension) using an archive program and a text editor...changing the jar does not rely on tomcat/guacd at all.

I presume you mean that either the login screen is not loading, does not load according to the changes in the extension or results in some other unexpected result. Please more clearly explain how it is not working. IE: what does it do that is not expected and what is the expectation.

I recommend checking log files, like /var/log/messages (may be different in Ubuntu) to look for errors related to this extension when loading the web GUI.

Also, I recommend reading the wiki (and what it links to), seeing if the un-modified jar loads and ensuring file ownership, permissions, etc are correct. The unmodified part is important. I cannot help with issues caused by your attempts to customize the jar...thats on you to research and work out.
